using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class New_Player_Controller : MonoBehaviour
{
    public Rigidbody RB;
    public float moveSpeed;

    Vector2 moveInput;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
        moveInput.x = Input.GetAxis("Horizontal");
        moveInput.y = Input.GetAxis("Vertical");
        moveInput.Normalize();

        RB.velocity = new Vector3(moveInput.x * moveSpeed, RB.velocity.y , moveInput.y * moveSpeed);
    }
}
